sudo: required
services:
  - docker

before_install:
  - docker build -t e3cd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true e3cd/react-test npm test -- --watchAll=false

after_success:
  - docker build -t e3cd/multi-client ./client
  - docker build -t e3cd/multi-nginx ./nginx
  - docker build -t e3cd/multi-server ./server
  - docker build -t e3cd/multi-worker ./worker
  # log in to cli, bypass wizard
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push them to docker hub thru docker cli
  - docker push e3cd/multi-client
  - docker push e3cd/multi-nginx
  - docker push e3cd/multi-server
  - docker push e3cd/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-585043354208
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
